### ISSUE TITLE
Nginx support is broken

### ISSUE THREAD

**Issue by schneems** [heroku/buildpacks-php#186]
## Expected

When deploying an app that uses PHP + Nginx (as outlined in https://devcenter.heroku.com/articles/custom-php-settings) on the cedar platform, it should also work in `pack build`

## Actual

Booting an nginx server fails:

```
$ docker run -it --rm --env PORT=5006 -p 5006:5006 php-image-name
DOCUMENT_ROOT changed to 'web/'
Assuming RAM to be 512M Bytes
Available RAM is 512M Bytes
Number of CPU cores is 12
PHP memory_limit is 128M Bytes
Calculated number of workers based on RAM and CPU cores is 48
Maximum number of workers that fit available RAM at memory_limit is 4
Limiting number of workers to 4
Starting php-fpm with 4 workers...
Starting nginx...
nginx: [emerg] mkdir() "/app/.heroku/php/var/run/nginx/client_body_temp" failed (2: No such file or directory)
Process exited unexpectedly: nginx, shutting down...
Stopping php-fpm gracefully...
Shutdown complete.
$ echo $?
70
```

## Reproduction

Setup:

```
$ git clone https://github.com/heroku/php-getting-started
$ cd php-getting-started
$ echo "web: heroku-php-nginx web/" > Procfile
$ git add .; git commit -m next
```

Verify it works on Heroku:

```
$ heroku create
$ git status && cat Procfile
On branch main
Your branch is ahead of 'origin/main' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
web: heroku-php-nginx web/
$ git push heroku
Enumerating objects: 243, done.
Counting objects: 100% (243/243), done.
Delta compression using up to 12 threads
Compressing objects: 100% (133/133), done.
Writing objects: 100% (243/243), 82.62 KiB | 41.31 MiB/s, done.
Total 243 (delta 96), reused 234 (delta 92), pack-reused 0 (from 0)
remote: Resolving deltas: 100% (96/96), done.
remote: Updated 17 paths from 7e98dc1
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Building on the Heroku-24 stack
remote: -----> Determining which buildpack to use for this app
remote: -----> PHP app detected
remote: -----> Bootstrapping...
remote: -----> Preparing platform package installation...
remote: -----> Installing platform packages...
remote:        - php (8.4.6)
remote:        - apache (2.4.63)
remote:        - composer (2.8.8)
remote:        - nginx (1.26.3)
...
remote:        Generating optimized autoload files
remote:        10 packages you are using are looking for funding.
remote:        Use the `composer fund` command to find out more!
remote: -----> Preparing runtime environment...
remote: -----> Checking for additional extensions to install...
remote: -----> Discovering process types
remote:        Procfile declares types -> web
remote:
remote: -----> Compressing...
remote:        Done: 20.2M
remote: -----> Launching...
remote:        Released v3
remote:        https://arcane-taiga-47528-4ff25f230e63.herokuapp.com/ deployed to Heroku
remote:
remote: Verifying deploy... done.
To https://git.heroku.com/arcane-taiga-47528.git
$ curl -I https://arcane-taiga-47528-4ff25f230e63.herokuapp.com/
HTTP/1.1 200 OK
```

Build locally with deployed version of `heroku/php` buildpack:

```
$ pack build php-image-name --path . --clear-cache
Digest: sha256:1f8c4f74030b31af122cbcccd9da975bd136a1076af2e3567bbf1a27c50ac0a3
Status: Image is up to date for heroku/builder:24
24: Pulling from heroku/heroku
Digest: sha256:c697e8808410892d54125b850854b908105dbae1c8e335255b9523c7f4e75516
Status: Image is up to date for heroku/heroku:24
===> ANALYZING
===> DETECTING
2 of 3 buildpacks participating
heroku/php      0.2.4
heroku/procfile 4.2.1
===> RESTORING
Skipping buildpack layer analysis
===> BUILDING

[Bootstrapping]

[Preparing platform packages installation]

[Installing platform packages]
No composer.lock file present. Updating dependencies to latest instead of installing from lock file. See https://getcomposer.org/install for more information.
Loading composer repositories with package information
Updating dependencies
Lock file operations: 26 installs, 0 updates, 0 removals
  - Locking fig/http-message-util (1.1.5)
  - Locking heroku-sys/composer (2.8.2)
  - Locking heroku-sys/php (8.3.13)
  - Locking heroku/installer-plugin (1.8.0)
  - Locking laravel/serializable-closure (v1.3.7)
  - Locking monolog/monolog (3.8.0)

...

[Preparing Composer runtime environment]

## Procfile Buildpack

- Processes from `Procfile`
  - web: `heroku-php-nginx web/`
- Done (finished in < 0.1s)
===> EXPORTING
Adding layer 'heroku/php:composer_env'
Adding layer 'heroku/php:platform'
Adding layer 'heroku/php:webservers'
Reusing layer 'buildpacksio/lifecycle:launch.sbom'
Added 1/1 app layer(s)
Reusing layer 'buildpacksio/lifecycle:launcher'
Adding layer 'buildpacksio/lifecycle:config'
Reusing layer 'buildpacksio/lifecycle:process-types'
Adding label 'io.buildpacks.lifecycle.metadata'
Adding label 'io.buildpacks.build.metadata'
Adding label 'io.buildpacks.project.metadata'
Setting default process type 'web'
Saving php-image-name...
*** Images (fcd85c6270cc):
      php-image-name
Adding cache layer 'heroku/php:composer_cache'
Adding cache layer 'heroku/php:platform_cache'
Successfully built image php-image-name
```

Booting the nginx webserver fails

```
$ docker run -it --rm --env PORT=5006 -p 5006:5006 php-image-name
DOCUMENT_ROOT changed to 'web/'
Assuming RAM to be 512M Bytes
Available RAM is 512M Bytes
Number of CPU cores is 12
PHP memory_limit is 128M Bytes
Calculated number of workers based on RAM and CPU cores is 48
Maximum number of workers that fit available RAM at memory_limit is 4
Limiting number of workers to 4
Starting php-fpm with 4 workers...
Starting nginx...
nginx: [emerg] mkdir() "/app/.heroku/php/var/run/nginx/client_body_temp" failed (2: No such file or directory)
Process exited unexpectedly: nginx, shutting down...
Stopping php-fpm gracefully...
Shutdown complete.
$ echo $?
70
```

 GUS-W-13169735

**Comment by schneems** [comment]
Updated the internal docs to state that it's not currently supported https://devcenter.heroku.com/admin/articles/diff/2054/v49..v50

**Comment by felegy** [comment]
I created a workaround for the 22 builder, an entrypoint script that creates the required directories.

**config/heroku-php-nginx.sh**
```
#!/bin/sh

set -eu

mkdir -p /app/.heroku/php/var/run/nginx
mkdir -p /app/.heroku/php/var/run/nginx/client_body_temp
mkdir -p /app/.heroku/php/var/run/nginx/proxy_temp
mkdir -p /app/.heroku/php/var/run/nginx/fastcgi_temp
mkdir -p /app/.heroku/php/var/run/nginx/uwsgi_temp
mkdir -p /app/.heroku/php/var/run/nginx/scgi_temp
cp -rav /layers/heroku_php/platform /app/.heroku/php

exec $*
```
Usage:

**Procfile:**
```
web: sh config/heroku-php-nginx.sh heroku-php-nginx -C config/nginx.conf -i config/php.ini web
```

It still doesn’t work with the 24 builder, and the workaround above is not suitable there.
```
mkdir: cannot create directory '/app': Permission denied
```

**Comment by felegy** [comment]
I made another workaround. It solves the problem in Kubernetes deployments, and with this the 24 builder and the 24 stack image also work. The essence of the solution is an initContainer:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-deployment
  labels:
    app: wp-app
spec:
  replicas: 1
# revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: wp-app
  template:
    metadata:
      labels:
        app: wp-app
    spec:
      imagePullSecrets:
      - name: github-container-registry
      volumes:
      - name: nginx
        emptyDir: {}
      initContainers:
      - name: init-heroku-nginx
        image: {{ .Values.wp.image }}
        imagePullPolicy: Always
        command:
        - sh
        - -c
        - |
          set -e
          mkdir -p /app/.heroku/php/var/run/nginx/{client_body_temp,proxy_temp,fastcgi_temp,uwsgi_temp,scgi_temp}
          chown -R 1000:1000 /app/.heroku/php/var/run/nginx
        volumeMounts:
        - name: nginx
          mountPath: "/app/.heroku/php/var/run/nginx"
          readOnly: false
```

This is the full deployment.yaml for complete understanding:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-deployment
  labels:
    app: wp-app
spec:
  replicas: 1
# revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: wp-app
  template:
    metadata:
      labels:
        app: wp-app
    spec:
      imagePullSecrets:
      - name: github-container-registry
      volumes:
      - name: nginx
        emptyDir: {}
      initContainers:
      - name: init-heroku-nginx
        image: {{ .Values.wp.image }}
        imagePullPolicy: Always
        command:
        - sh
        - -c
        - |
          set -e
          mkdir -p /app/.heroku/php/var/run/nginx/{client_body_temp,proxy_temp,fastcgi_temp,uwsgi_temp,scgi_temp}
          chown -R 1000:1000 /app/.heroku/php/var/run/nginx
        volumeMounts:
        - name: nginx
          mountPath: "/app/.heroku/php/var/run/nginx"
          readOnly: false
      containers:
      - name: wp-app
        image: {{ .Values.wp.image }}
        imagePullPolicy: Always
        command: 
        - {{ .Values.wp.command | default "web" | quote }}
        resources:
          requests:
            memory: 128M
            cpu: 100m
          limits:
            memory: 512M
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: env
        - secretRef:
            name: secret-env
        - secretRef:
            name: db-connection
        livenessProbe:
          failureThreshold: 3
          httpGet:
            httpHeaders:
            - name: Host
              value: {{ .Values.wp.host }}
            - name: X-Forwarded-Proto
              value: https
            path: /wp/wp-cron.php?nocache
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 30
        readinessProbe:
          failureThreshold: 3
          httpGet:
            httpHeaders:
            - name: Host
              value: {{ .Values.wp.host }}
            - name: X-Forwarded-Proto
              value: https
            path: /?nocache
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 30
        volumeMounts:
        - name: nginx
          mountPath: "/app/.heroku/php/var/run/nginx"
          readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: wp
spec:
  selector:
    app: wp-app
  ports:
  - name: wp
    protocol: TCP
    port: 5000
    targetPort: 5000
```
